services:
  postgres:
    image: postgres:15-alpine
    container_name: lumix-postgres
    environment:
      POSTGRES_USER: lumix
      POSTGRES_PASSWORD: lumix_password
      POSTGRES_DB: lumix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lumix-network

  redis:
    image: redis:7-alpine
    container_name: lumix-redis
    ports:
      - "6379:6379"
    networks:
      - lumix-network

  chat-server:
    build:
      context: .
      dockerfile: apps/chat-server/Dockerfile
    container_name: lumix-chat-server
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://lumix:lumix_password@postgres:5432/lumix
      REDIS_URL: redis://lumix-redis:6379
      ION_ENDPOINT: ${ION_ENDPOINT}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - migrate
    networks:
      - lumix-network

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: lumix-client
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://lumix:lumix_password@postgres:5432/lumix
      AUTH_TRUST_HOST: "true"
      AUTH_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
      AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
      AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
      AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      NEXT_PUBLIC_TENOR_API_KEY: ${NEXT_PUBLIC_TENOR_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - chat-server
      - migrate
      - sfu
    networks:
      - lumix-network

  sfu:
    image: pionwebrtc/ion-sfu:latest-jsonrpc
    ports:
      - "5000-5200:5000-5200/udp"
      - "7000:7000"
  
  migrate:
    build:
      context: .
      dockerfile: PrismaMigration.Dockerfile
    container_name: prisma-migrate-container
    environment:
      - DIRECT_URL=postgresql://lumix:lumix_password@postgres:5432/lumix
    depends_on:
      - postgres
    networks:
      - lumix-network

volumes:
  postgres_data:

networks:
  lumix-network:
    driver: bridge
